### PR TITLE
Toward 1.0

### PR DESCRIPTION
**Pull request by FaceDeer**
This brings in a whole lot of changes I've been working on to bring this mod toward what I'd call a "complete" state. The most important changes in this pull are:

- Small changes to recipe table format - single output stack only to simplify compatibility with the rest of Minetest, and burntime/cooktime is now represented by a "heat" item that exists only as a virtual item in furnace reactions.
- Simplified legacy recipe import interface
- Ability to export and import recipes in both the form of a Lua table and in a GraphXML file for easy visualization.
- Player inventory crafting interface replacement, supporting both unified_inventory and sfinv.
- Craftitem template, which acts as a sort of portable crafting table (use item to open the interface)
- Added pre_craft and post_craft callback registration to allow for things like default:book_written duplication recipes.

I still need to integrate a crafting guide into unified_inventory, it currently still shows the old crafting guide. There's a working crafting guide in sfinv, though.

### CODE REVIEW

**Comment by tacotexmex** [comment]
Awesome, need to test this!

**Comment by tacotexmex** [comment]
Speaking of GraphXML, are you familiar with its Markdown-esque counterparts? Check out GraphViz for example: https://demo.codimd.org/s/features#Diagrams

**Comment by FaceDeer** [comment]
Looks simple enough to write, I'll see about adding this as an output option. Not sure if I can make it an input option, though, it may depend on whether I can embed hidden metadata into the graph in a convenient way.

**Comment by tacotexmex** [comment]
Thanks! Input option would be glorious, as it would enable a new type of collaboration on recipes (git backed Markdown, or that CodiMD service)

**Comment by FaceDeer** [comment]
I just hammered together a DOT export option. You might want to take care to filter the recipes included in its output down to a manageable number when you use it with Graphviz, when I tried graphing all of the recipes I had in my test server at once it ground my computer to a halt. :)

**Pull request merged**
